version: "2"
services:

  wotopenapi:
    build: ./wot_openapi/
    ports:
        - 5001:5000
    networks:
        app_subnet:
            ipv4_address: 172.16.1.5 
                      
networks:
  app_subnet: 
    ipam:
        config: 
            - subnet: 172.16.1.0/24   
